### ISSUE TITLE
Why password-file?

### ISSUE THREAD

**Issue by Abhishekkarunakaran** [omkarium/rufendec#1]
Why u used password-file, instead of entering password?

**Comment by omkarium** [comment]
@Abhishekkarunakaran Hi, so my reasoning for using the password-file is that, if you enter the password directly in the command line/terminal, anyone who gains access to your machine can see the logs especially when you are using GNULinux based os. The commands you type in the terminal are logged at several places like var.log, bash profile history etc.  It's not safe. Which is why you put the password into a file and later put some file access restrictions only for your users or select users. 

Note: I am releasing a new version taking few comments I received into consideration. Namely, introducing the AES - GCM mode with a --mode option parameter. And a PBDFK2 for key generation.  Planning to release it very soon. Follow the repo so you get a notification. Let me know if you have any questions. Thanks.

**Comment by Abhishekkarunakaran** [comment]
Thanks man 🙌

**Comment by omkarium** [comment]
@Abhishekkarunakaran The GCM mode and PBKDF2 feature is now added to the code with version 0.3.0. You can test the new feature. There should be no performance loss when you choose GCM over ECB, and GCM is must secure. I am closing this issue now.
